name: React-Demo
on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: NPM Install
              run: npm ci
              working-directory: ./react-demo
            - name: Build app
              run: npm run build
              working-directory: ./react-demo
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: react-demo-build
                folder: react-demo/build